
# Generated by CodiumAI
from App.Repos.VerslagRepo import VerslagRepo


# Dependencies:
# pip install pytest-mock
import pytest

class TestUpdateVerslag:

    # Successfully updates date field when provided
    def test_update_date_field(self, mocker):
        # Arrange
        mock_db = mocker.Mock()
        verslag_repo = VerslagRepo(mock_db)
        verslag_id = 1
        new_date = "2023-10-01"
        mock_verslag = mocker.Mock()
        mock_db.query.return_value.filter.return_value.first.return_value = mock_verslag

        # Act
        result = verslag_repo.update_verslag(verslag_id, date=new_date)

        # Assert
        assert result == mock_verslag
        assert mock_verslag.date == new_date
        mock_db.commit.assert_called_once()
        mock_db.refresh.assert_called_once_with(mock_verslag)

    # Verslag with given verslag_id does not exist
    def test_verslag_does_not_exist(self, mocker):
        # Arrange
        mock_db = mocker.Mock()
        verslag_repo = VerslagRepo(mock_db)
        verslag_id = 999
        mock_db.query.return_value.filter.return_value.first.return_value = None

        # Act
        result = verslag_repo.update_verslag(verslag_id, date="2023-10-01")

        # Assert
        assert result is None
        mock_db.commit.assert_not_called()
        mock_db.refresh.assert_not_called()

        # pytest Tests/verslagtests/update_verslagtest.py