name: Test Workflow

on:
  push:
    branches: [ Groep-3 ]
  pull_request:
    branches: [ Groep-3 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Workflow is running"
