name: Groep-3 Unit Test oefenen

on:
  push:
    branches: [ Groep-3 ]
  pull_request:
    branches: [ Groep-3 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pymysql
        pip install pytest pytest-cov  # Installeer pytest en coverage
        pip install pytest-mock

    - name: Run tests
      run: |
        pytest backend/tests/update_report_test.py  # Voer je tests uit
