name: All_Linter

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
  pull_request:
    branches:
      - groep-2
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@a8150b40c89574adb5f68bf9502b890a236a06b3
        uses: super-linter/super-linter@v5.7.2
        env: 
          GITHUB_TOKEN: ${{Secrets.GITHUB_TOKEN}}
