name: Build and Deploy
on:
  push:
    branches:
      - "groep6_b2d_Hassan"

env:
  TEST: envs_kunnen ook global

jobs:
  build:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Welkom123456!
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: SUPERSECRETKEY
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    runs-on: ubuntu-latest
    steps:
      - name: Log checked branch
        run:  echo "Checked out branch ${{ github.ref }}"
      - name: Pulling repo
        uses: actions/checkout@v2
        
      - name: Install python version 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: | 
          sudo apt install libmariadb3 libmariadb-dev -y
          pip install -r requirements.txt
      - name: Unittest
        run: echo "Dit is een test"

  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Pulling repo
          uses: actions/checkout@v2
        - name: Create artefact
          run: |
            mkdir dist
            pwd
            cp -r App main.py requirements.txt dist/
            ls
        - name: Reboot Server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 52.232.64.59
            username: groep6
            password: Welkom123456!
            script: |
              sudo reboot
              exit
        - name: Wait for server to reboot
          run: sleep 20
        - name: Deploy to ubuntu server
          uses: garygrossgarten/github-action-scp@release
          with:
            local: dist
            remote: API
            host: 52.232.64.59
            username: groep6
            password: Welkom123456!
        - name: Start API
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 52.232.64.59
            username: groep6
            password: Welkom123456!
            script: |
              python3 -m pip install --upgrade pip
              pip install mariadb
              sudo apt-get update -y
              sudo apt install libmariadb3 libmariadb-dev -y
              cd API
              sudo pip install -r requirements.txt
              nohup sudo uvicorn main:app --host 0.0.0.0 --port 80 >api.log 2>&1 </dev/null &
              exit