name: Build and Deploy
on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

env:
  TEST: envs_kunnen ook global

jobs:
  build:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: SUPERSECRETKEY
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    runs-on: ubuntu-latest
    steps:
      - name: Log checked out branch
        run:  echo "Checked out branch ${{ github.ref }}"
      - name: Pulling git repo
        uses: actions/checkout@v2
        
      - name: Install python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: | 
          sudo apt install libmariadb3 libmariadb-dev
          pip install -r requirements.txt
      - name: UnitTests
        run: echo "Dit is een nep test"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Pulling git repo
  #       uses: actions/checkout@v2
  #     - name: Deploy to ubuntu server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: 52.166.135.125
  #         username: groep1
  #         password: Welkomwelkom123!
  #         script: |
  #           cd app/src
  #           git clone https://github.com/ZuydUniversity/B2C6_B2D_Backend.git .
  #           git checkout groep_1_B2D_Said_Amghar
  #           fastapi run main.py

  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Pulling git repo
          uses: actions/checkout@v2
        - name: Deploy to ubuntu server
          uses: appleboy/ssh-action@master
          with:
            host: 52.166.135.125
            username: groep1
            password: Welkomwelkom123!
            script: |
              mkdir hetwerkt

  
