name: Build and Deploy
on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

jobs:
  API_Setup:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: | 
          sudo apt install libmariadb3 libmariadb-dev
          pip install -r requirements.txt
      - name: UnitTesten
        run: echo "Dit is een nep test"
  

