name: Backend CI

on:
  push:
    branches:
      - Dev-Group-4

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
#### Acties op Github Runnner
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install libmariadb3 libmariadb-dev -y
          pip install -r requirements.txt

      - name: Unit-Tests
        run: echo "Dit is geen echte test"

      - name: Build API artifacts
        run: | 
          mkdir Backend
          cp -r App main.py requirements.txt Backend/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Backend
          path: Backend

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Backend
          path: Backend
          
#### Acties op VM
      - name: Clean Old Artefact
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: 20.160.97.126
           username: groep4user
           password: WelkomWelkom123!
           script: |
            sudo rm -rf Backend

      - name: Deploy to ubuntu server
        uses: garygrossgarten/github-action-scp@release
        with:
#### Runner 
           local: Backend
#### Azure VM
           remote: Backend
           host: 20.160.97.126
           username: groep4user
           password: WelkomWelkom123!
           
      - name: Install dependencies on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: 20.160.97.126
           username: groep4user
           password: WelkomWelkom123!
           script: |
              sudo apt install python3-pip -y
              python -m pip install --upgrade pip
              pip install mariadb
              sudo apt get update -y
              sudo apt install libmariadb3 libmariadb-dev -y
              cd Backend
              sudo pip install -r requirements.txt

      - name: Reboot Server
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: 20.160.97.126
           username: groep4user
           password: WelkomWelkom123!
           script: |
            sudo reboot
            exit

      - name: Wait for server to reboot
        run: sleep 20

      - name: Start backend & Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: 20.160.97.126
           username: groep4user
           password: WelkomWelkom123!
           script: |
              ( cd Frontend ; nohup sudo npm run start -- -p 80 >frontend.log 2>&1 </dev/null & )
              ( cd Backend ; nohup sudo uvicorn main:app --host 0.0.0.0 --port 8000 >backend.log 2>&1 </dev/null & )

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Backend build succeeded :tada:"}' ${{ secrets.GROEP_4_SLACK_WEBHOOK }}

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Backend build failed :x:"}' ${{ secrets.GROEP_4_SLACK_WEBHOOK }}
