name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: groep2          #name of your Azure Web App
  PYTHON_VERSION: '3.8'              #Python version to use

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pul git repo
        uses: actions/checkout@v2
      
      - name: 'Deploy to Azure'
        id: deploy-to-webapp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 108.142.148.168
          username: groep2
          password: groep-2Hexagon
          run: git clone https://github.com/ZuydUniversity/B2C6_B2D_Backend.git
