name: run_on_ssh

on:
  push:
  workflow_dispatch:

jobs:
  check_code:
    uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/check_code.yml@Groep-2
  run_on_ssh:
    needs: [check_code]
    uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/run_on_ssh.yml@Groep-2
