name: Backend CI

on:
  push:
    branches:
      - Dev-Group-4

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install system dependencies
        run: |
          sudo apt install libmariadb3 libmariadb-dev -y
          pip install -r requirements.txt

      - name: Unit-Tests
        run: echo "Dit is geen echte test"

      - name: Build API artifacts
        run: | 
          mkdir Backend
          cp -r App main.py requirements.txt Backend/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Backend
          path: Backend

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Backend
          path: Backend

      - name: Reboot Server
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.AZURE_VM_HOST_GROEP4 }} 
         username: ${{ secrets.AZURE_VM_USERNAME_GROEP4 }}  
         password: ${{ secrets.AZURE_VM_PASSWORD_GROEP4 }}
         script: |
          sudo reboot
          exit

      - name: Wait for server to reboot
        run: sleep 20

      - name: Clean Old Artefact
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.AZURE_VM_HOST_GROEP4 }} 
         username: ${{ secrets.AZURE_VM_USERNAME_GROEP4 }}  
         password: ${{ secrets.AZURE_VM_PASSWORD_GROEP4 }}
         script: |
          sudo rm -rf Backend

      - name: Deploy to ubuntu server
        uses: garygrossgarten/github-action-scp@release
        with:
           local: Backend
           remote: Backend
           host: ${{ secrets.AZURE_VM_HOST_GROEP4 }} 
           username: ${{ secrets.AZURE_VM_USERNAME_GROEP4 }}  
           password: ${{ secrets.AZURE_VM_PASSWORD_GROEP4 }}
           
      - name: Install dependencies on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST_GROEP4 }} 
          username: ${{ secrets.AZURE_VM_USERNAME_GROEP4 }}  
          password: ${{ secrets.AZURE_VM_PASSWORD_GROEP4 }}
          script: |
              sudo apt install python3-pip -y
              python -m pip install --upgrade pip
              pip install mariadb
              sudo apt get update -y
              sudo apt install libmariadb3 libmariadb-dev -y
              cd Backend
              sudo pip install -r requirements.txt

      - name: Start API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST_GROEP4 }} 
          username: ${{ secrets.AZURE_VM_USERNAME_GROEP4 }}  
          password: ${{ secrets.AZURE_VM_PASSWORD_GROEP4 }}
          script: |
              ( cd Backend ; nohup sudo uvicorn main:app --host 0.0.0.0 --port 8000 >backend.log 2>&1 </dev/null & )

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Backend build succeeded :tada:"}' ${{ secrets.GROEP_4_SLACK_WEBHOOK }}

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Backend build failed :x:"}' ${{ secrets.GROEP_4_SLACK_WEBHOOK }}
