name: main       

on:
  push:

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    secrets: inherit

  build:
    needs: testing
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/build_push_docker.yml@groep-2
    secrets: inherit
  build-fail-notify:
    needs: build
    if: ${{ failure() }}
    uses:
      ZuydUniversity/B2C6_B2D_IAS/.github/workflows/send_slack_webhook.yml@groep-2
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":rotating_light: [BACKEND] build: FAILED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, workflow info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :rotating_light:"

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/run_docker_via_ssh.yml@groep-2
    secrets: inherit
  deploy-fail-notify:
    needs: deploy
    if: ${{ failure() }}
    uses:
      ZuydUniversity/B2C6_B2D_IAS/.github/workflows/send_slack_webhook.yml@groep-2
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":rotating_light: [BACKEND] deploy: FAILED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, workflow info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :rotating_light:"
  deploy-success-notify:
    needs: deploy
    if: ${{ success() }}
    uses:
      ZuydUniversity/B2C6_B2D_IAS/.github/workflows/send_slack_webhook.yml@groep-2
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":white_check_mark: [BACKEND] build: SUCCEEDED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, workflow info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :white_check_mark:"
    
