name: main

on:
  push:

jobs:
  testing:
    uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/testing.yml@Groep-2
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.GROEP_2_SLACK_WEBHOOK }}

  build:
    needs: testing
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/build_upload_docker.yml@groep-2
    secrets:
      GROEP_2_DOCKERHUB_USERNAME: ${{ secrets.GROEP_2_DOCKERHUB_USERNAME }}
      GROEP_2_DOCKERHUB_TOKEN: ${{ secrets.GROEP_2_DOCKERHUB_TOKEN }}
      GROEP_2_DOCKERHUB_REPO_NAME: ${{ secrets.GROEP_2_DOCKERHUB_BACKEND_REPO_NAME }}

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/run_docker_via_ssh.yml@groep-2
