name: main     

on:
  push:

jobs:
  #testing:
  #  uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/testing.yml@Groep-2
  #  secrets: inherit

  build:
    #needs: testing
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/build_push_docker.yml@groep-2
    secrets: inherit

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/run_docker_via_ssh.yml@groep-2
