name: main 

on:
  push:

jobs:
  #testing:
  #  uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/testing.yml@Groep-2
  #  secrets: inherit

  build:
    #needs: testing
    uses: ./.github/workflows/build_push_docker.yml
    secrets:
      GROEP_2_DOCKERHUB_USERNAME: ${{ secrets.GROEP_2_DOCKERHUB_USERNAME }}
      GROEP_2_DOCKERHUB_TOKEN: ${{ secrets.GROEP_2_DOCKERHUB_TOKEN }}
      GROEP_2_DOCKERHUB_BACKEND_REPO_NAME: ${{ secrets.GROEP_2_DOCKERHUB_BACKEND_REPO_NAME }}

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/run_docker_via_ssh.yml@groep-2
