name: run_on_ssh

on:
  push:
  workflow_dispatch:

jobs:
  upload_on_ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create zip
        run: |
          zip -r . current.zip
          ls -la
      
      - name: 'Deploy to Azure'
        id: deploy-to-webapp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 108.142.148.168
          username: groep2
          password: groep-2Hexagon
          run: git clone https://github.com/ZuydUniversity/B2C6_B2D_Backend.git
