name: run_on_ssh

on:
  push:
  workflow_dispatch:

env:
  REMOTE_DIR: 'backend_server'  # "~/<remote_dir>"

jobs:
  upload_on_ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to ubuntu server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: $REMOTE_DIR
          host: 108.142.148.168
          username: groep2
          password: groep-2Hexagon
      
