name: run_on_ssh

on:
  push:
  workflow_dispatch:

env:
  LOCAL_DIST: "/tmp/dist"
  REMOTE_HOST: "108.142.148.168"
  REMOTE_USER: "groep2" 
  REMOTE_PASSWORD: "groep-2Hexagon"
  REMOTE_DIST: "/tmp/app"  # "~/<remote_dir>"

jobs:
  upload_on_ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare dist
        run: |
          cp -r . "${{ env.LOCAL_DIST }}"
          rm -rf "${{ env.LOCAL_DIST }}/.git"

      - name: Deploy to ubuntu server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.LOCAL_DIST }}
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          password: ${{ env.REMOTE_PASSWORD }}
          remote: ${{ env.REMOTE_DIST }}

  run_on_ssh:
    runs-on: ubuntu-latest
    needs: upload_on_ssh
    steps:
        - uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ env.REMOTE_HOST }}
            username: ${{ env.REMOTE_USER }}
            password: ${{ env.REMOTE_PASSWORD }}
            script: |
              ps -faux
              pkill fastapi  # kill old instance
              cd "${{ env.REMOTE_DIST }}"
              python3 -m venv venv
              pip install -r requirements.txt
              fastapi run main.py
