name: Groep-3 Unit Test oefenen

on:
  push:
    branches: [ "Groep-3" ]
  pull_request:
    branches: [ "Groep-3" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pymysql
        pip install pytest pytest-cov pytest-mock

    - name: Run tests
      id: run_tests
      run: pytest backend/tests/update_report_test.py

    - name: Send notification on slack using webhooks
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text":"Dit is een test"
          }
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          

