name: Groep-3 Unit Test oefenen

on:
  push:
    branches: [ "Groep-3" ]
  pull_request:
    branches: [ "Groep-3" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pymysql
        pip install pytest pytest-cov pytest-mock

    - name: Run tests
      id: run_tests
      run: pytest backend/tests/update_report_test.py

    - name: Send Slack notification on success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Test succeeded in Groep-3 branch:  $GITHUB_RUN_URL"}' \
        ${{ secrets.GROEP_DRIE }}

    - name: Send Slack notification on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Test failed in Groep-3 branch:  $GITHUB_RUN_URL"}' \
        ${{ secrets.GROEP_DRIE }}
