name: testing_linter

on:
  workflow_call:

jobs:
  main:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: super-linter/super-linter@v5.7.2
