name: Groep-3 Unit Test oefenen

on:
  push:
    branches: [ "Groep-3" ]
  pull_request:
    branches: [ "Groep-3" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pymysql
        pip install pytest pytest-cov pytest-mock

    - name: Run tests
      id: run_tests
      run: pytest backend/tests/update_report_test.py

    - name: Slack Notification on Success!
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: good
        SLACK_ICON: https://cdn.discordapp.com/attachments/1015233182209159201/1247122042848022538/7503aw.png
        SLACK_MESSAGE: 'Test Automation Report https://github.com/ZuydUniversity/B2C6_B2D_Backend/actions/runs/${{github.run_id}}'
        SLACK_TITLE: 'Unit Test Success'
        SLACK_WEBHOOK: ${{ secrets.GROEP_DRIE }}

    - name: Slack Notification on Failure!
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: danger
        SLACK_ICON: https://cdn.discordapp.com/attachments/1015233182209159201/1247122042848022538/7503aw.png
        SLACK_MESSAGE: 'Test Automation Report https://github.com/ZuydUniversity/B2C6_B2D_Backend/actions/runs/${{github.run_id}}'
        SLACK_TITLE: 'Unit Test Failure'
        SLACK_WEBHOOK: ${{ secrets.GROEP_DRIE }}

