name: Groep-3 Unit Test oefenen

on:
  push:
    branches: 
      - "Groep-3"
  pull_request:
    branches: 
      - "Groep-3"

  
  workflow_dispatch:

#permissions:
# contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy pymysql
        pip install pytest pytest-cov  # Installeer pytest en coverage
        pip install pytest-mock

    - name: Run tests
      run: |
        pytest backend/tests/update_report_test.py  # Voer je tests uit
        slackNotification:
          name: Slack Notification
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_WEBHOOK: https://hooks.slack.com/services/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