name: testing_linter

on:
  workflow_call:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.GROEP_2_SLACK_WEBHOOK }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  main:
    name: Run linters
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@a8150b40c89574adb5f68bf9502b890a236a06b3
        uses: super-linter/super-linter@v5.7.2
        env: 
          GITHUB_TOKEN: ${{Secrets.GITHUB_TOKEN}}

  notify:
    runs-on: ubuntu-20.04
    needs: [main]
    if: ${{ always() }}
    steps:
      - uses: slackapi/slack-github-action@v1.26.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GH workflow `linter`: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ needs.main.result }}>"
                  }
                }
              ]
            }

