name: testing 

on:
  workflow_call:
    secrets:
      GROEP_2_SLACK_WEBHOOK:
        required: true
  pull_request:

jobs:
  codeql:
    uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/testing_codeql.yml@Groep-2
  linter:
    uses: ZuydUniversity/B2C6_B2D_Backend/.github/workflows/testing_linter.yml@Groep-2
  notify:
    #needs: [codeql, linter]
    needs: codeql
    if: ${{ failure() }}
    uses:
      ZuydUniversity/B2C6_B2D_IAS/.github/workflows/send_slack_webhook.yml@groep-2
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":rotating_light: [BACKEND] tests: FAILED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, test info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :rotating_light:"
